### ISSUE TITLE
Plans to support the `weights` argument?

### ISSUE THREAD

**Issue by elliottmorris** [mgoplerud/vglmer#12]
Other packages for multilevel models allow the inclusion of sample weights in the model with the `weights` argument in the function call. This is the main thing missing for my (very narrow, very needy) needs. Wonder if it's something that's been roadmapped?

Great packages. Faster and more stable estimate than I get from the Stan VI implemented in BRMS, and more flexible than lme4 since we can use stable deep interactions...

**Comment by mgoplerud** [comment]
In the past, I have dealt with sample weights by using the `cbind(success, failure) ~ .` formulation in `vglmer`, `lme4` and others and using the weighted counts of success and failures. 

This can be permitted for non-integer outcomes in `vglmer` using `control = vglmer_control(force_whole = FALSE)`. I include a reprex below with a comparison with how `lme4` treats weights. The one thing to note is that multiplying the weights by some factor (e.g., x10) will affect the regularization strength so should be explored, based on number of "pseudo" observations, etc. 

Do you think this will work for your purposes?

``` r
library(vglmer)
library(lme4)
#> Loading required package: Matrix
set.seed(1234)
N <- 1000
weights <- rexp(N, rate = 1/5)
weights <- weights/sum(weights) * N
x <- rnorm(N)
g <- sample(letters, N, replace = TRUE)
y <- rbinom(N, 1, plogis(x * 2 + rnorm(26, sd = 2)[match(g, letters)]))
dta <- data.frame(
  y, x, g, w = weights
)

fit_lme4 <- glmer(
  y ~ x + (1 | g), 
  data = dta, 
  family = binomial())
fit_vglmer <- vglmer(
  y ~ x + (1 | g), data = dta,
  family = 'binomial'
)
plot(fitted(fit_lme4), plogis(fitted(fit_vglmer)))
abline(a=0,b=1)
```

![](https://i.imgur.com/U7KZmHh.png)

``` r


fit_lme4_weight <- glmer(
  y ~ x + (1 | g), data = dta,
  family = binomial(), weights = w
)
#> Warning in eval(family$initialize, rho): non-integer #successes in a binomial
#> glm!
fit_lme4_alt <- glmer(
  cbind(y * w, (1-y) * w) ~ x + (1 | g), data = dta,
  family = binomial()
)
#> Warning in eval(family$initialize, rho): non-integer counts in a binomial glm!
# Check that two different methods coincide
print(
  all.equal(fitted(fit_lme4_weight) , fitted(fit_lme4_alt))
)
#> [1] TRUE
fit_vglmer_weight <- vglmer(
  cbind(y * w, (1-y) * w) ~ x + (1 | g), data = dta,
  family = 'binomial',
  control = vglmer_control(force_whole = FALSE)
)
#> Warning in vglmer(cbind(y * w, (1 - y) * w) ~ x + (1 | g), data = dta, family =
#> "binomial", : Non-integer numbers in y

plot(fitted(fit_lme4_weight), 
     plogis(fitted(fit_vglmer_weight)))  
```

![](https://i.imgur.com/px2JHWu.png)

``` r

# Note that multiplying the weights x10 changes lme4 estimates
# and will do the same for vglmer
fit_lme4_weight_2 <- glmer(
  y ~ x + (1 | g), data = dta,
  family = binomial(), weights = w * 10
)
#> Warning in eval(family$initialize, rho): non-integer #successes in a binomial
#> glm!

plot(fitted(fit_lme4_weight), fitted(fit_lme4_weight_2))
abline(a=0,b=1,col='red')
```

![](https://i.imgur.com/YY4sbPj.png)

<sup>Created on 2023-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by elliottmorris** [comment]
This seems to work for me. Thanks!
