### ISSUE TITLE
Matrix error with many FEs

### ISSUE THREAD

**Issue by kuriwaki** [mgoplerud/vglmer#13]
I'm trying vglmer with one RE and many interacted FEs (i.e. interactions of conjoint categorical variables) relative to the sample size. At a certain number of covariates, I get two types of errors:

1. In a n = 100 dataset I get this. This is n << k (number of covariates) so I guess it's out of scope.

```
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'a' in selecting a method for function 'solve': error in evaluating the argument 'x' in selecting a method for function 't': the leading minor of order 324 is not positive
```

2. I get a somewhat different error for a larger dataset also with a lot of FE interactions. I don't think this is `n < k`.

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'a' in selecting a method for function 'solve': internal_chm_factor: Cholesky factorization failed
In addition: Warning message:
In Cholesky(..sparse2d(.M2sym(as(A, "CsparseMatrix"))), perm = perm,  :
  Cholmod warning 'not positive definite' at file ../Cholesky/t_cholmod_rowfac.c, line 430
```

I'm probably throwing too much at it, and it's clearly not a error with the package. but if you have further insight on these error messages, that would be helpful. unfortunately I can't share the data.

**Comment by mgoplerud** [comment]
Hello,

A few thoughts:

My first instinct is that those errors suggest that FE matrix is not full rank and the internal Cholesky factorization failing when the variational distribution for `q(beta)` is updated. 

If you created the model matrix and checked its rank, does that show anything in the second case?

Another issue could be perfect separation of the outcome is binomial, so I'd check whether the second one runs with `family='linear'` 

Finally, would it be sensible in your use case to try random effects for the categorical variables + random effects on the interactions?

If none of those seem to help, I can try to dig into this more.

**Comment by kuriwaki** [comment]
Many thanks, I will check the rank and close the issue if it's something unclear in my specification. 

I've been running a linear model. 

I think REs on everything conceptually works too. In vglmer would that be as fast / faster than treating a thounsand + variables a fixed effects?

**Comment by mgoplerud** [comment]
I think it should be much faster as it can rely on the variational approximation of independence across REs - so I'd suspect many fold improvement in computational time.

**Comment by kuriwaki** [comment]
In the example I've been working with, it was possible to run pretty large-k models. But with all the interactions, the default R settings seem to run out of memory. I think that's our issue though, so we will think more about the right coefficients. Thanks for your ideas.
