### ISSUE TITLE
Support for survey sampling weights?

### ISSUE THREAD

**Issue by coletl** [mgoplerud/vglmer#14]
Hi, I really appreciate this package and accompanying papers! I'm currently trying to use your methods for MRP. 

I couldn't find anything about weights (outside of the super learner docs), so I'm wondering whether `vglmer` can fit models with sampling weights, like those from a nationally representative survey. If that's not yet supported, could you add that as a feature request?

Thanks!
Cole

**Comment by mgoplerud** [comment]
Hello! Glad to hear that the package is useful; there was a discussion of survey weights #12 that might be useful (e.g., using non-integer `cbind(success, failure) ~ .` ; let me know if that seems like it'll address your issue!

**Comment by coletl** [comment]
Oh wow, that's clever. Looks like exactly what I need! And thank you for the quick reply — really appreciate it.

**Comment by mgoplerud** [comment]
Great! Glad it seems like it'll help. Let me know if you encounter any other issues.
