### ISSUE TITLE
Failure on CRAN

### ISSUE THREAD

**Issue by hadley** [mgoplerud/vglmer#16]
Unfortunately the recent waldo release broke your package on CRAN because it no longer imports tibble, and your package was implicitly depending on it. The easiest fix is to just make the dependency explicit, by adding tibble to Suggests.

Many apologies for the hassle. Unfortunately we didn't discover this prior to CRAN release because we had a bug in the code that runs our revdep checks 🙁.

**Comment by mgoplerud** [comment]
Thanks; this is addressed in version 1.0.6, submitted to CRAN.
